export const COMPETITOR_MAP: Record<string, string[]> = {
  "Scaler": ["upGrad", "Great Learning", "Coding Ninjas", "Masai School", "Newton School", "Simplilearn", "Coursera", "Udemy", "Udacity", "Skillshare"],
  "Qure.ai": ["Aidoc", "PathAI", "Zebra Medical Vision", "Viz.ai", "Tempus", "Enlitic", "Arterys", "DeepMind Health", "Caption Health", "Butterfly Network"],
  "Swiggy": ["Zomato", "Uber Eats", "Blinkit", "Dunzo", "Zepto", "EatSure", "Deliveroo", "DoorDash", "Grubhub", "Just Eat"],
  "mPokket": ["KreditBee", "CASHe", "MoneyTap", "LazyPay", "PaySense", "EarlySalary", "Navi", "Slice", "ZestMoney", "Bajaj Finserv"],
  "AstraZeneca": ["Pfizer", "Novartis", "Roche", "Johnson & Johnson", "Merck", "GSK", "Sanofi", "AbbVie", "Bayer", "Eli Lilly"],
  "Capgemini": ["Accenture", "TCS", "Infosys", "Wipro", "Cognizant", "HCLTech", "IBM", "Deloitte", "Tech Mahindra", "PwC"],
  "Indian Oil": ["BPCL", "HPCL", "Reliance Industries", "Nayara Energy", "Shell", "TotalEnergies", "ONGC", "ExxonMobil", "Chevron", "Gazprom"],
  "Reddit": ["Quora", "X", "Discord", "Facebook Groups", "Tumblr", "4chan", "Stack Overflow", "Medium", "Telegram", "LinkedIn"],
  "Plum": ["Mamaearth", "Minimalist", "Nykaa", "WOW Skin Science", "Sugar Cosmetics", "Dot & Key", "Biotique", "Forest Essentials", "Himalaya", "Lakme"],
  "Observe.ai": ["Gong", "Chorus.ai", "CallMiner", "NICE Nexidia", "Talkdesk", "Five9", "Verint", "Genesys", "Balto", "Tethr"],
  "Demandbase": ["6sense", "ZoomInfo", "HubSpot", "Salesforce", "Marketo", "Pardot", "Clearbit", "Leadfeeder", "Apollo.io", "Terminus"],
  "JumpCloud": ["Okta", "Microsoft Azure AD", "OneLogin", "Ping Identity", "Duo Security", "IBM Security Verify", "Google Workspace IAM", "Auth0", "CyberArk", "SailPoint"],
  "Murf AI": ["ElevenLabs", "Play.ht", "Descript", "Resemble AI", "Lovo.ai", "Speechify", "WellSaid Labs", "Replica Studios", "Coqui AI", "Amazon Polly"],
  "Avaamo": ["Kore.ai", "Yellow.ai", "Cognigy", "Rasa", "IBM Watson Assistant", "Google Dialogflow", "Amazon Lex", "LivePerson", "Drift", "Intercom"],
  "Zeta": ["Razorpay", "Stripe", "PayU", "Cashfree", "Adyen", "Square", "Paytm Payments", "PhonePe", "Visa", "Mastercard"],
  "Jar": ["Groww", "Zerodha", "Upstox", "INDmoney", "ET Money", "Paytm Money", "Kuvera", "Coin by Zerodha", "Smallcase", "Angel One"],
  "Bright Money": ["MoneyTap", "KreditBee", "CASHe", "Navi", "PaySense", "ZestMoney", "Slice", "EarlySalary", "LazyPay", "Bajaj Finserv"],
  "Enkash": ["RazorpayX", "Open", "PayU", "Cashfree", "Stripe", "Paytm Business", "Instamojo", "Airwallex", "Wise", "Brex"],
  "Great Learning": ["upGrad", "Simplilearn", "Coursera", "Udacity", "edX", "Scaler", "Coding Ninjas", "Skillshare", "Udemy", "FutureLearn"],
  "Emeritus": ["upGrad", "Coursera", "edX", "Simplilearn", "Great Learning", "Udacity", "FutureLearn", "Skillshare", "ExecOnline", "2U"],
  "Adda Education": ["Unacademy", "BYJU’S", "Testbook", "Gradeup", "PhysicsWallah", "Vedantu", "Toppr", "Khan Academy", "Embibe", "Career Launcher"],
  "Udhyam Learning": ["Pratham", "Teach For India", "NSDC", "Skill India", "Udacity", "Coursera", "edX", "upGrad", "Simplilearn", "Khan Academy"],
  "College Vidya": ["Shiksha", "CollegeDekho", "Leverage Edu", "upGrad", "Coursera", "edX", "Simplilearn", "Careers360", "Collegedunia", "Unacademy"],
  "UPES": ["Amity University", "LPU", "Manipal University", "Symbiosis", "Sharda University", "Chandigarh University", "SRM", "VIT", "NMIMS", "Ashoka University"],
  "Pearl Academy": ["NIFT", "NID", "JD Institute", "LISAA School", "Vogue Institute", "Amity School of Design", "Arch College", "Istituto Marangoni", "Parsons", "FIT"],
  "National Law School (NLS)": ["NALSAR", "NLUD", "WBNUJS", "GNLU", "NLIU", "HNLU", "RGNUL", "JGLS", "Symbiosis Law School", "Amity Law School"],
  "BCG": ["McKinsey", "Bain & Company", "Deloitte Consulting", "Accenture Strategy", "Kearney", "Oliver Wyman", "EY Consulting", "PwC Advisory", "Roland Berger", "Strategy&"],
  "Sattva Consulting": ["Dalberg", "FSG", "BCG", "Bain", "Deloitte", "EY", "PwC", "KPMG", "Bridgespan Group", "Accenture"],
  "Engie": ["Siemens Energy", "GE Power", "Schneider Electric", "ABB", "TotalEnergies", "Shell", "EDF Energy", "Enel", "Iberdrola", "NextEra Energy"],
  "Suez India": ["Veolia", "Tata Projects", "L&T", "Thermax", "VA Tech Wabag", "Ion Exchange", "Xylem", "Ecolab", "Aquatech", "GE Water"],
  "Goldi Solar": ["Adani Solar", "Tata Power Solar", "Vikram Solar", "Waaree Energies", "RenewSys", "Azure Power", "First Solar", "Canadian Solar", "JinkoSolar", "Trina Solar"],
  "SleepyCat": ["Wakefit", "Sleepyhead", "The Sleep Company", "Sunday Mattress", "Duroflex", "Kurlon", "Nilkamal Sleep", "IKEA Mattresses", "Springtek", "Flo Mattress"],
  "Blue Tokai": ["Third Wave Coffee", "Starbucks", "CCD", "Barista", "Tim Hortons", "Costa Coffee", "Rage Coffee", "Sleepy Owl", "Nescafe", "Bru"],
  "Zappfresh": ["Licious", "FreshToHome", "TenderCuts", "Meatigo", "BigBasket", "Amazon Fresh", "Nature’s Basket", "Spencer’s", "Reliance Fresh", "Grofers"],
  "Swiggy Instamart": ["Blinkit", "Zepto", "Dunzo", "BigBasket", "Amazon Fresh", "Flipkart Quick", "JioMart", "Nature’s Basket", "Spencer’s", "Reliance Fresh"],
  "Hasbro": ["Mattel", "LEGO", "Spin Master", "Funko", "Bandai Namco", "MGA Entertainment", "Playmobil", "Jakks Pacific", "Fisher-Price", "Ravensburger"],
  "Coupang": ["Amazon", "Flipkart", "Alibaba", "JD.com", "Rakuten", "Shopee", "Lazada", "eBay", "Walmart", "Target"],
  "Google": ["Microsoft", "Amazon", "Apple", "Meta", "IBM", "Oracle", "Salesforce", "Adobe", "NVIDIA", "OpenAI"],
  "Netflix": ["Amazon Prime Video", "Disney+ Hotstar", "Hulu", "HBO Max", "Apple TV+", "YouTube", "SonyLIV", "Zee5", "MX Player", "Peacock"],
  "Qualcomm": ["Intel", "NVIDIA", "AMD", "MediaTek", "Broadcom", "Samsung Semiconductor", "Apple Silicon", "IBM", "ARM", "Marvell"],
  "Panasonic": ["Sony", "Samsung", "LG", "Philips", "Whirlpool", "Bosch", "Hitachi", "Toshiba", "Sharp", "Haier"],
  "vivo": ["Xiaomi", "Samsung", "Oppo", "Realme", "OnePlus", "Apple", "Motorola", "Nokia", "Huawei", "Tecno"],
  "HiSense": ["Samsung", "LG", "Sony", "TCL", "Panasonic", "Philips", "Xiaomi", "Haier", "Sharp", "Toshiba"],
  "Simple Energy": ["Ola Electric", "Ather Energy", "TVS Electric", "Bajaj Chetak", "Hero Electric", "Ampere", "Okinawa", "Revolt Motors", "Pure EV", "Ultraviolette"],
  "Montra Electric": ["Tata Motors EV", "Mahindra Electric", "Ashok Leyland EV", "Olectra", "Switch Mobility", "Euler Motors", "Omega Seiki", "Piaggio EV", "Hero Electric", "Ather Energy"],
  "Pixxel": ["Planet Labs", "Maxar", "BlackSky", "Satellogic", "ICEYE", "Spire Global", "Capella Space", "Airbus Defence", "Thales Alenia", "NASA"]
};
